[project]
name = "gemini-cli-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0",
    "uvicorn>=0.30.0",
    "pydantic>=2.0.0",
]
